### ISSUE TITLE
Advanced Management is broken

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/Module-LGSL_with_Img_Mod#3]
When you to go the LGSL Admin page from Administration menu, you can click the advanced Management button. If you then save from this Advanced Management page, it breaks everything and only keeps the first line. Also the content of this text box before modifying anything looks weird with lot of antislashes at the end of the first line:

> 
> killingfloor2  :62.210.178.64                 :3333  :22571 :0      :0      :0 :\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
> killingfloor2  :62.210.178.64                 :5555  :24793 :0      :0      :0 :
> killingfloor2  :62.210.178.64                 :2565  :21803 :0      :0      :0 :
> killingfloor2  :62.210.178.64                 :3565  :22803 :0      :0      :0 :
> redorchestra2  :62.210.178.64                 :7777  :27015 :0      :0      :0 :
> redorchestra2  :62.210.178.64                 :7787  :27025 :0      :0      :0 :
> redorchestra2  :62.210.178.64                 :11110 :30348 :0      :0      :0 :
> redorchestra2  :62.210.178.64                 :7797  :27035 :0      :0      :0 :
> redorchestra2  :62.210.178.64                 :8888  :28126 :0      :0      :0 :
> redorchestra2  :62.210.178.64                 :6666  :25904 :0      :0      :0 :
> redorchestra   :62.210.178.64                 :7757  :7758  :0      :0      :0 :
> redorchestra   :62.210.178.64                 :7575  :7576  :0      :0      :0 :
> 
>         
>.

 The above is what it contains right now, if I click save button with or without modifying anything, it results in this:

> 
> killingfloor2  :62.210.178.64                 :3333  :22571 :0      :0      :0 :\r\nkillingfloor2
> 
>         
>.

Note the blank line at the end followed by another blank line with a few spaces, like the text area before saving it.

edit: ok Github messed with my quotes, adding a dot on a new line to keep the rest before it.
edit2: weird when I edit my test I can see the two blank lines and the spaces on the last one. it does not show outside the edition mode.

**Comment by Adjokip** [comment]
The issue is with line 64: https://github.com/OpenGamePanel/Module-LGSL_with_Img_Mod/blob/master/modules/lgsl_with_img_mod/lgsl_files/lgsl_admin.php#L64

`explode` wasn't functioning as it should when exploding on `\r\n` characters. Yet, if you `var_dump($_POST['form_list']);` you'd see the `\r\n` is present:

~~~
"source         :game.hg-gaming.net            :27015 :27015 :0      :0      :0 :\r\nsource         :xxx.xxx.xxx.xxx                :27015 :27015 :0      :0      :0 :\r\n\r\n        "
~~~

Okay, so what about: `var_dump(strrpos($_POST['form_list'], "\n"));` to get the position in the string where `\n` is? result was `(bool) false` ... so it doesn't exist in the string? yet, from above we do see it.

Apparently, it has double backslashes for some reason. I'm not sure why it's being posted like that.

Changing line 64 to the following fixes it. Which will also work in the future if the strange behaviour stops.
~~~
$form_lines = preg_split('/\r?\n|\r|(\\\r)?\\\n|\\\r/', $_POST['form_list']);
~~~
